// reclama261 — cartas de reclamación y escalado (HTML imprimible), 6 idiomas
const T = {
  es: {
    claimTitle: 'Reclamación de compensación — Reglamento (CE) n.º 261/2004',
    to: 'A la atención de:', ref: 'Ref.', flight: 'Vuelo', date: 'Fecha del vuelo',
    route: 'Ruta', delay: 'Retraso a la llegada', event: 'Incidencia', amount: 'Importe reclamado',
    body1: 'Por la presente, el abajo firmante, en calidad de pasajero del vuelo indicado, reclama la compensación económica prevista en el artículo 7 del Reglamento (CE) n.º 261/2004.',
    body2: 'El vuelo sufrió la incidencia descrita, que supera los umbrales establecidos por el Tribunal de Justicia de la UE (asunto C-402/07, Sturgeon, y jurisprudencia concordante), sin que concurran circunstancias extraordinarias que eximan de la obligación.',
    citeIntro: 'La causa alegada por la compañía no la exime de responsabilidad conforme a la jurisprudencia del TJUE:',
    payment: 'Se requiere el pago de la cantidad indicada en un plazo de 14 días desde la recepción de esta carta, mediante transferencia a la siguiente cuenta:',
    deadline: 'Transcurrido dicho plazo sin abono, se presentará reclamación ante la autoridad nacional competente (AESA en España o el organismo equivalente) y, en su caso, la correspondiente demanda judicial, con los intereses y costas que procedan.',
    sign: 'Firmado:',
    events: { delay: 'Retraso ≥ 3 h', cancellation: 'Cancelación', denied_boarding: 'Denegación de embarque' },
    escTitle: 'Reclamación ante la autoridad — Reglamento (CE) n.º 261/2004',
    escBody: 'El abajo firmante presentó reclamación de compensación a la compañía aérea sin obtener el pago en plazo. Se solicita a este organismo que inste a la aerolínea al abono de la compensación prevista en el artículo 7, más los intereses que procedan.',
    docs: 'Documento generado por reclama261 · Información orientativa, no constituye asesoramiento jurídico. Adjuntar: tarjetas de embarque, reserva y justificantes.',
  },
  en: {
    claimTitle: 'Compensation claim — Regulation (EC) No 261/2004',
    to: 'For the attention of:', ref: 'Ref.', flight: 'Flight', date: 'Flight date',
    route: 'Route', delay: 'Arrival delay', event: 'Disruption', amount: 'Amount claimed',
    body1: 'The undersigned, as a passenger on the flight indicated, claims the compensation provided for in Article 7 of Regulation (EC) No 261/2004.',
    body2: 'The flight suffered the disruption described, exceeding the thresholds set by the Court of Justice of the EU (Case C-402/07, Sturgeon, and related case law), with no extraordinary circumstances exempting the obligation.',
    citeIntro: 'The reason given by the carrier does not exempt it under CJEU case law:',
    payment: 'Payment of the amount stated is required within 14 days of receipt of this letter, by bank transfer to:',
    deadline: 'If payment is not received within that period, a complaint will be filed with the competent national enforcement body and, where necessary, court proceedings initiated, including interest and costs.',
    sign: 'Signed:',
    events: { delay: 'Delay ≥ 3 h', cancellation: 'Cancellation', denied_boarding: 'Denied boarding' },
    escTitle: 'Complaint to the enforcement body — Regulation (EC) No 261/2004',
    escBody: 'The undersigned filed a compensation claim with the airline and received no payment within the deadline. This body is requested to order the airline to pay the compensation provided for in Article 7, plus applicable interest.',
    docs: 'Document generated by reclama261 · Informational only, not legal advice. Attach: boarding passes, booking and receipts.',
  },
  de: {
    claimTitle: 'Ausgleichsforderung — Verordnung (EG) Nr. 261/2004',
    to: 'Zu Händen:', ref: 'Az.', flight: 'Flug', date: 'Flugdatum',
    route: 'Strecke', delay: 'Ankunftsverspätung', event: 'Vorkommnis', amount: 'Geforderter Betrag',
    body1: 'Hiermit fordert der Unterzeichner als Fluggast des genannten Fluges die Ausgleichszahlung nach Artikel 7 der Verordnung (EG) Nr. 261/2004.',
    body2: 'Der Flug wies die beschriebene Störung auf, welche die vom Gerichtshof der EU festgelegten Schwellen überschreitet (C-402/07, Sturgeon), ohne dass außergewöhnliche Umstände vorliegen.',
    citeIntro: 'Der von der Airline genannte Grund befreit sie laut EuGH-Rechtsprechung nicht:',
    payment: 'Die Zahlung des genannten Betrags wird binnen 14 Tagen nach Erhalt dieses Schreibens per Überweisung erbeten auf:',
    deadline: 'Nach Ablauf der Frist wird Beschwerde bei der zuständigen Stelle (z. B. SÖP) und gegebenenfalls Klage erhoben, zuzüglich Zinsen und Kosten.',
    sign: 'Unterschrift:',
    events: { delay: 'Verspätung ≥ 3 h', cancellation: 'Annullierung', denied_boarding: 'Nichtbeförderung' },
    escTitle: 'Beschwerde bei der Behörde — Verordnung (EG) Nr. 261/2004',
    escBody: 'Der Unterzeichner hat die Airline erfolglos zur Zahlung aufgefordert. Die Behörde wird ersucht, die Airline zur Zahlung der Ausgleichsleistung nach Artikel 7 nebst Zinsen zu veranlassen.',
    docs: 'Dokument erstellt von reclama261 · Unverbindliche Information, keine Rechtsberatung. Anlagen: Bordkarten, Buchung und Belege.',
  },
  fr: {
    claimTitle: 'Demande d’indemnisation — Règlement (CE) n° 261/2004',
    to: 'À l’attention de :', ref: 'Réf.', flight: 'Vol', date: 'Date du vol',
    route: 'Itinéraire', delay: 'Retard à l’arrivée', event: 'Incident', amount: 'Montant réclamé',
    body1: 'Le soussigné, passager du vol indiqué, réclame l’indemnisation prévue à l’article 7 du règlement (CE) n° 261/2004.',
    body2: 'Le vol a subi l’incident décrit, dépassant les seuils fixés par la Cour de justice de l’UE (C-402/07, Sturgeon), sans circonstances extraordinaires exonératoires.',
    citeIntro: 'Le motif invoqué par la compagnie ne l’exonère pas selon la jurisprudence de la CJUE :',
    payment: 'Le paiement du montant indiqué est requis dans un délai de 14 jours à compter de la réception de la présente, par virement sur :',
    deadline: 'À défaut de paiement, une réclamation sera déposée auprès de l’autorité nationale compétente et, le cas échéant, une action en justice sera engagée, avec intérêts et dépens.',
    sign: 'Signature :',
    events: { delay: 'Retard ≥ 3 h', cancellation: 'Annulation', denied_boarding: 'Refus d’embarquement' },
    escTitle: 'Réclamation auprès de l’autorité — Règlement (CE) n° 261/2004',
    escBody: 'Le soussigné a vainement mis en demeure la compagnie. L’autorité est priée d’enjoindre la compagnie au paiement de l’indemnisation de l’article 7, majorée des intérêts.',
    docs: 'Document généré par reclama261 · Information indicative, ne constitue pas un conseil juridique. Joindre : cartes d’embarquement, réservation et justificatifs.',
  },
  it: {
    claimTitle: 'Richiesta di compensazione — Regolamento (CE) n. 261/2004',
    to: 'All’attenzione di:', ref: 'Rif.', flight: 'Volo', date: 'Data del volo',
    route: 'Tratta', delay: 'Ritardo all’arrivo', event: 'Disservizio', amount: 'Importo richiesto',
    body1: 'Il sottoscritto, passeggero del volo indicato, richiede la compensazione pecuniaria prevista dall’articolo 7 del regolamento (CE) n. 261/2004.',
    body2: 'Il volo ha subito il disservizio descritto, oltre le soglie fissate dalla Corte di giustizia UE (C-402/07, Sturgeon), senza circostanze eccezionali esimenti.',
    citeIntro: 'Il motivo addotto dalla compagnia non la esonera secondo la giurisprudenza della CGUE:',
    payment: 'Il pagamento dell’importo indicato è richiesto entro 14 giorni dal ricevimento della presente, tramite bonifico su:',
    deadline: 'In difetto, sarà presentato reclamo all’autorità nazionale competente (ENAC) e, se del caso, sarà promosso giudizio, con interessi e spese.',
    sign: 'Firma:',
    events: { delay: 'Ritardo ≥ 3 h', cancellation: 'Cancellazione', denied_boarding: 'Negato imbarco' },
    escTitle: 'Reclamo all’autorità — Regolamento (CE) n. 261/2004',
    escBody: 'Il sottoscritto ha diffidato invano la compagnia. Si chiede all’autorità di ingiungere il pagamento della compensazione di cui all’articolo 7, oltre interessi.',
    docs: 'Documento generato da reclama261 · Informativa, non costituisce consulenza legale. Allegare: carte d’imbarco, prenotazione e ricevute.',
  },
  pt: {
    claimTitle: 'Pedido de indemnização — Regulamento (CE) n.º 261/2004',
    to: 'Aos cuidados de:', ref: 'Ref.', flight: 'Voo', date: 'Data do voo',
    route: 'Rota', delay: 'Atraso à chegada', event: 'Ocorrência', amount: 'Montante reclamado',
    body1: 'O abaixo-assinado, passageiro do voo indicado, reclama a indemnização prevista no artigo 7.º do Regulamento (CE) n.º 261/2004.',
    body2: 'O voo sofreu a ocorrência descrita, ultrapassando os limiares fixados pelo Tribunal de Justiça da UE (C-402/07, Sturgeon), sem circunstâncias extraordinárias eximentes.',
    citeIntro: 'O motivo invocado pela companhia não a exonera segundo a jurisprudência do TJUE:',
    payment: 'O pagamento do montante indicado é exigido no prazo de 14 dias após a receção da presente, por transferência para:',
    deadline: 'Decorrido o prazo, será apresentada reclamação junto da autoridade nacional competente (ANAC) e, se necessário, intentada ação judicial, com juros e custas.',
    sign: 'Assinatura:',
    events: { delay: 'Atraso ≥ 3 h', cancellation: 'Cancelamento', denied_boarding: 'Recusa de embarque' },
    escTitle: 'Reclamação à autoridade — Regulamento (CE) n.º 261/2004',
    escBody: 'O abaixo-assinado interpelou a companhia sem sucesso. Solicita-se à autoridade que intime a companhia ao pagamento da indemnização do artigo 7.º, acrescida de juros.',
    docs: 'Documento gerado pelo reclama261 · Informação orientativa, não constitui aconselhamento jurídico. Anexar: cartões de embarque, reserva e comprovativos.',
  },
};

const ORGS = {
  aesa: {
    name: 'AESA — Agencia Estatal de Seguridad Aérea (España)',
    address: 'Avda. del General Perón 40, 28020 Madrid · https://sede.seguridadaerea.gob.es',
  },
  sop: {
    name: 'SÖP — Schlichtungsstelle für den öffentlichen Personenverkehr (Alemania)',
    address: 'Fasanenstraße 81, 10623 Berlin · https://soep-online.de',
  },
  caa: {
    name: 'CAA — Civil Aviation Authority (Reino Unido)',
    address: 'Aviation House, Beehive Ring Road, Crawley · https://www.caa.co.uk/passengers',
  },
  generic: {
    name: 'Autoridad nacional competente / Organismo de resolución alternativa (ADR)',
    address: 'Dirección según país de reclamación',
  },
};

function h(claim, ev, t, cite) {
  const route = `${claim.departureIata} → ${claim.arrivalIata}`;
  const eventLabel = t.events[claim.eventType] || claim.eventType;
  const delayText = ev.delayMin != null ? `${Math.floor(ev.delayMin / 60)} h ${ev.delayMin % 60} min` : '—';
  const amountText = `${ev.totalAmount ?? (ev.amountPerPassenger ?? 0) * (claim.passengers || 1)} €`;
  const iban = claim.iban || (t === T.es ? 'IBAN del pasajero' : 'passenger IBAN');
  return `
<table class="meta">
  <tr><td>${t.flight}</td><td>${claim.flightNumber || ''}</td></tr>
  <tr><td>${t.date}</td><td>${claim.flightDate || ''}</td></tr>
  <tr><td>${t.route}</td><td>${route}${ev.distanceKm ? ` (${ev.distanceKm} km)` : ''}</td></tr>
  <tr><td>${t.event}</td><td>${eventLabel}</td></tr>
  <tr><td>${t.delay}</td><td>${delayText}</td></tr>
  <tr><td>${t.amount}</td><td class="amount">${amountText}</td></tr>
</table>
<p>${t.body1}</p>
<p>${t.body2}</p>
${cite ? `<div class="case"><strong>${t.citeIntro}</strong> ${cite.citation} — ${cite.ruling}</div>` : ''}
<p>${t.payment} <strong>${iban}</strong>.</p>
<p>${t.deadline}</p>`;
}

function shell(title, sub, lang, inner, foot, signer, passengerName = '') {
  return `<!doctype html>
<html lang="${lang}">
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  @page { margin: 2.2cm; }
  body { font-family: Georgia, 'Times New Roman', serif; font-size: 12.5pt; line-height: 1.55; color: #1c1a17; max-width: 17cm; margin: 0 auto; padding: 24px; }
  h1 { font-size: 16pt; letter-spacing: -0.01em; margin: 0 0 4px; }
  .sub { color: #6b665c; font-size: 10.5pt; margin-bottom: 18px; }
  table.meta { width: 100%; border-collapse: collapse; margin: 12px 0 18px; font-family: 'Segoe UI', Arial, sans-serif; font-size: 10.5pt; }
  table.meta td { border-bottom: 1px solid #d8d3c7; padding: 6px 8px; vertical-align: top; }
  table.meta td:first-child { width: 38%; color: #6b665c; }
  .amount { font-size: 14pt; font-weight: bold; }
  .case { border-left: 3px solid #b8952e; padding: 6px 12px; margin: 10px 0; background: #faf7ee; font-size: 11pt; }
  .sign { margin-top: 34px; }
  .foot { margin-top: 28px; font-size: 9pt; color: #8a8578; border-top: 1px solid #d8d3c7; padding-top: 8px; }
</style>
</head>
<body>
<h1>${title}</h1>
<div class="sub">${sub}</div>
${inner}
<div class="sign">${signer}<br><br><br>${passengerName}</div>
<div class="foot">${foot}</div>
</body>
</html>`;
}

export function generateClaimLetter(claim, lang = 'es') {
  const t = T[lang] || T.es;
  const ev = claim.evaluation || {};
  const cite = ev.extraordinary?.matched?.[0];
  const inner = h(claim, ev, t, cite);
  return shell(
    t.claimTitle,
    `${t.to} ${claim.airline || ''} · ${t.ref} ${claim.id}`,
    lang, inner, t.docs, t.sign, claim.passengerName || '',
  );
}

export function generateEscalationLetter(claim, org = 'aesa', lang = 'es') {
  const t = T[lang] || T.es;
  const ev = claim.evaluation || {};
  const o = ORGS[org] || ORGS.generic;
  const cite = ev.extraordinary?.matched?.[0];
  const inner = h(claim, ev, t, cite).replace(
    new RegExp(`<p>${t.payment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[^]*?</p>`), '',
  ) + `<p>${t.escBody}</p>`;
  return shell(
    t.escTitle,
    `${t.to} ${o.name} · ${o.address} · ${t.ref} ${claim.id}`,
    lang, inner, t.docs, t.sign, claim.passengerName || '',
  );
}
